### ISSUE TITLE
Error "Could not decode XML" when importing APK (AndroidManifest.xml)

### ISSUE THREAD

**Issue by reox** [secure-software-engineering/CodeInspect#151]
I tried to import several APK files and i get this Error all the time:

```
Could not decode XML
  V. v. 0.2 Nightly; 1353 Built on 05/08/15 15:08
brut.androlib.AndrolibException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:199)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:139)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
	at de.codeinspect.core.e.a(SourceFile)
	at de.codeinspect.core.cg.a(SourceFile)
	at de.codeinspect.core.cg.a(SourceFile)
	at de.codeinspect.core.ce.a(SourceFile)
	at de.codeinspect.core.ch$1.execute(SourceFile)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:106)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:118)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:294)
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.<init>(XmlPullWrapperFactory.java:52)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.newInstance(XmlPullWrapperFactory.java:29)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:49)
	... 16 more

  Could not decode XML
```

This happens always for the AndroidManifest.xml file, because it is empty after the import. Is it a problem with my systems JDK/JRE/Android SDK? It is definitly not a problem with the APK i'm using, the error is shown on every file I import. Also the AndroidManifest.xml are not striped.

**Comment by srasthofer** [comment]
Thanks for reporting the issue. Could you share the apk with us that we can reproduce the error?

**Comment by MarcMil** [comment]
OK, just recently we integrated the newest APKTool builds into CodeInspect.
I guess this problem is a direct cause of that fact.
Probably the current nightly build is simply broken regarding importing all APKs. I check this right now.

**Comment by marcellmajor** [comment]
I have the same and looking forward for the fix.

**Comment by MarcMil** [comment]
I have found and fixed this issue. However it takes a while to rebuild.
After the rebuild I will confirm that the nightly build does not suffer this problem anymore and will announce it on this bug report.

**Comment by MarcMil** [comment]
I have checked the new build.
Please redownload CodeInspect, this issue should be fixed now.

Sorry for the inconvenience.

**Comment by reox** [comment]
@MarcMil thanks for the quick response! I Also noticed, that there is no content in the assets, lib and res folder folder. Does this have something to do with this bug? Otherwise i can create a new issue item.
