### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by phros** [secure-software-engineering/CodeInspect#197]
Hi,

when importing the com.avira.android app (and several other apps) into Codeinspect and lunching it without any modifications I get the following exeption and the app crashes instantly.

Using: CodeInspect v. 1594, built on 15/11/15 15:11 

```
11-18 13:16:00.406: E/AndroidRuntime(3151): FATAL EXCEPTION: main
11-18 13:16:00.406: E/AndroidRuntime(3151): java.lang.NoClassDefFoundError: android.os.BaseBundle
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at io.fabric.sdk.android.services.common.j.b(j.jimple:87)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at io.fabric.sdk.android.services.common.j.a(j.jimple:32)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at com.crashlytics.android.Crashlytics.onPreExecute(Crashlytics.jimple:1247)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at com.crashlytics.android.Crashlytics.onPreExecute(Crashlytics.jimple:1217)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at io.fabric.sdk.android.m.a(m.jimple:68)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at io.fabric.sdk.android.n.initialize(n.jimple:229)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at io.fabric.sdk.android.f.a(f.jimple:392)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at io.fabric.sdk.android.f.a(f.jimple:255)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at com.avira.android.ApplicationService.onCreate(ApplicationService.jimple:586)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3954)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at android.app.ActivityThread.access$1300(ActivityThread.java:123)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1185)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at android.os.Looper.loop(Looper.java:137)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at android.app.ActivityThread.main(ActivityThread.java:4424)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at java.lang.reflect.Method.invoke(Method.java:511)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
11-18 13:16:00.406: E/AndroidRuntime(3151): 	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by MarcMil** [comment]
Please try to select the API version of your device in the "Import APK" window.

**Comment by phros** [comment]
Cool, now it works. Thanks!

Maybe you can show an alert when the users selects an emulator with an API Version differing to the one selected in project settings.
