### ISSUE TITLE
APK fails to install

### ISSUE THREAD

**Issue by JanSteffan** [secure-software-engineering/CodeInspect#73]
When trying to run this APK from CodeInspect, there is an error (The generated Output.apk can't be installed on emulator "Failure [INSTALL_FAILED_DEXOPT]") and some warnings related to compilation (It's not clear whether installation fails becaus of these warnings or anohter issue):
https://www.dropbox.com/s/vympka96bpzdqq7/com.cerience.reader.app-1.apk?dl=0
```
Could not resolve org.apache.http.'annotation'.GuardedBy	BasicIdGenerator.jimple	/com.cerience.reader.app-1.apk/Sources/org.apache.http.impl.client.cache	line 6	Compilation Problem
Could not resolve org.apache.http.'annotation'.Immutable	HeaderConstants.jimple	/com.cerience.reader.app-1.apk/Sources/org.apache.http.client.cache	line 1	Compilation Problem
Could not resolve org.apache.http.'annotation'.NotThreadSafe	InputLimit.jimple	/com.cerience.reader.app-1.apk/Sources/org.apache.http.client.cache	line 1	Compilation Problem
Could not resolve org.apache.http.'annotation'.ThreadSafe	BasicHttpCacheStorage.jimple	/com.cerience.reader.app-1.apk/Sources/org.apache.http.impl.client.cache	line 1	Compilation Problem
Could not resolve org.apache.http.util.EntityUtils.consume with the return type void and the parameters (org.apache.http.HttpEntity)	BasicHttpCache.jimple	/com.cerience.reader.app-1.apk/Sources/org.apache.http.impl.client.cache	line 164	Compilation Problem
Could not resolve org.apache.http.util.EntityUtils.consumeQuietly with the return type void and the parameters (org.apache.http.HttpEntity)	BasicHttpCache.jimple	/com.cerience.reader.app-1.apk/Sources/org.apache.http.impl.client.cache	line 170	Compilation Problem
```
(The original APK can be installed and run in the same emulator.)

**Comment by MarcMil** [comment]
Interestingly, it seems that dexlib writes annotations in the wrong order.
E/dalvikvm( 1090): Out-of-order encoded_annotation name_idx: 0xcb56 then 0x9f2a
E/dalvikvm( 1090): Trouble with item 69 @ offset 0x2e9ad4
E/dalvikvm( 1090): Swap of section type 2004 failed
E/dalvikvm( 1090): ERROR: Byte swap + verify failed
E/dalvikvm( 1090): Optimization failed

This seemed to be fixed in https://code.google.com/p/smali/issues/detail?id=211, however the fix is already included in the version of soot, which CodeInspect uses. A more detailed analysis is required.

**Comment by StevenArzt** [comment]
Do you have a duplicate annotation name? Soot should check for such issues, but I'm not totally sure whether this validity check indeed happens everywhere, including automatically generated annotations such as the DefaultAnnotation stuff.

**Comment by JanSteffan** [comment]
in case it helps, here's the logcat output during isntallation:
```
D/PackageManager(  342): Renaming /data/app/vmdl86220849.tmp to /data/app/com.cerience.reader.app-1
I/art     (  342): DexFile_isDexOptNeeded failed to open oat file '/data/dalvik-cache/arm/data@app@com.cerience.reader.app-1@base.apk@classes.dex' for file location '/data/app/com.cerience.reader.app-1/base.apk': Failed to open oat filename for reading: No such file or directory
I/art     (  342): DexFile_isDexOptNeeded failed to open oat file '/data/app/com.cerience.reader.app-1/arm/base.odex' for file location '/data/app/com.cerience.reader.app-1/base.apk': Failed to open oat filename for reading: No such file or directory
I/PackageManager(  342): Running dexopt on: /data/app/com.cerience.reader.app-1/base.apk pkg=com.cerience.reader.app isa=arm vmSafeMode=false
I/dex2oat ( 1307): /system/bin/dex2oat --zip-fd=6 --zip-location=/data/app/com.cerience.reader.app-1/base.apk --oat-fd=7 --oat-location=/data/dalvik-cache/arm/data@app@com.cerience.reader.app-1@base.apk@classes.dex --instruction-set=arm --instruction-set-features=default --runtime-arg -Xms64m --runtime-arg -Xmx512m
E/dex2oat ( 1307): Failed to open dex from file descriptor for zip file '/data/app/com.cerience.reader.app-1/base.apk': Failure to verify dex file '/data/app/com.cerience.reader.app-1/base.apk': Out-of-order annotation_element name_idx: b498 then 8841
I/dex2oat ( 1307): dex2oat took 1.520s (threads: 1)
E/installd(   67): DexInv: --- END '/data/app/com.cerience.reader.app-1/base.apk' --- status=0x0100, process failed
W/PackageManager(  342): Package couldn't be installed in /data/app/com.cerience.reader.app-1
W/PackageManager(  342): com.android.server.pm.PackageManagerException: scanPackageLI
W/PackageManager(  342):        at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:5716)
W/PackageManager(  342):        at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5057)
W/PackageManager(  342):        at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:9881)
W/PackageManager(  342):        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:10389)
W/PackageManager(  342):        at com.android.server.pm.PackageManagerService.access$2300(PackageManagerService.java:230)
W/PackageManager(  342):        at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:8335)
W/PackageManager(  342):        at android.os.Handler.handleCallback(Handler.java:739)
W/PackageManager(  342):        at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager(  342):        at android.os.Looper.loop(Looper.java:135)
W/PackageManager(  342):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager(  342):        at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by MarcMil** [comment]
Seems to be fixed on the new nightly builds.
