### ISSUE TITLE
CodeInspect not detecting sdk folder in Mac OSX

### ISSUE THREAD

**Issue by ofercas** [secure-software-engineering/CodeInspect#78]
Can execute android from command, and the sdk folder is configured correctly in the Android Preferences. I tried to chmod 777 the sdk folder, but getting the same message. 
Any ideas?

Cannot run program "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools/android" (in directory "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools"): error=3, No such process
Cannot run program "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools/android" (in directory "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools"): error=3, No such process
  java.io.IOException: Cannot run program "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools/android" (in directory "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools"): error=3, No such process
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at de.darmstadt.tu.jimclipse.base.J.a(Unknown Source)
	at de.darmstadt.tu.jimclipse.base.J.a(Unknown Source)
	at de.darmstadt.tu.jimclipse.base.J.e(Unknown Source)
	at de.darmstadt.tu.jimclipse.base.eclipseinterfaces.AVDHandler.execute(Unknown Source)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:825)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:701)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$6(HandledContributionItem.java:685)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:613)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4188)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4031)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.io.IOException: error=3, No such process
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:185)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 51 more

  Cannot run program "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools/android" (in directory "/Users/user/Desktop/Android/adt-bundle-mac-x86_64-20140702/sdk/tools"): error=3, No such process

**Comment by srasthofer** [comment]
@MarcMil: I can also confirm that the latest version has some problems with MacOS. Before I enter the license code, the following pop up appears:
![bildschirmfoto 2015-03-08 um 21 59 19](https://cloud.githubusercontent.com/assets/3647928/6547660/95f485d8-c5de-11e4-8fb8-02b9089020cd.png)
@ofercas: We try to fix this soon.

**Comment by srasthofer** [comment]
#### QuickFix ####
@ofercas Please download our nightly build. We created a quick fix for your problem. Did it solve your issue?

**Comment by ofercas** [comment]
@srasthofer Thanks for the quick response. Its working fine.
There is other issue now, When trying to debug / execute an application getting the following messages:
![Uploading Screen Shot 2015-03-09 at 9.42.22 AM.png . . .]()

**Comment by srasthofer** [comment]
Unfortunately, I can not see the screenshot. Could you try uploading it again?

**Comment by ofercas** [comment]
![screen shot 2015-03-09 at 9 42 22 am](https://cloud.githubusercontent.com/assets/10746360/6551477/d192b46c-c641-11e4-85c7-a1eae3cdecd7.png)

**Comment by srasthofer** [comment]
I closed the #78 issue and opened a new #80 issue.
