### ISSUE TITLE
Resource error in gmail apk

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#83]
Hi:

There is an error importing gmail apk, 

Trace as follows:

```
resource spec: 0x0101048c
resource spec: 0x0101048c
  brut.androlib.err.UndefinedResObject: resource spec: 0x0101048c
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:57)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:53)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:581)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:344)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:133)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
	at de.darmstadt.tu.jimclipse.base.d.a(Unknown Source)
	at de.darmstadt.tu.jimclipse.base.bM.a(Unknown Source)
	at de.darmstadt.tu.jimclipse.base.bM.a(Unknown Source)
	at de.darmstadt.tu.jimclipse.base.bK.a(Unknown Source)
	at de.darmstadt.tu.jimclipse.base.bN$1.execute(Unknown Source)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:106)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:118)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

  resource spec: 0x0101048c
```

![screenshot from 2015-03-11 16 45 45](https://cloud.githubusercontent.com/assets/2270027/6592914/19cac940-c80e-11e4-87a4-ad0437fb3eb5.png)

After ignoring the error, following additional errors come into being:

![screenshot from 2015-03-11 16 59 53](https://cloud.githubusercontent.com/assets/2270027/6593099/39fd52ee-c810-11e4-9188-f8df3063e490.png)

Sample attached: http://box.myqsc.com/-33172088

**Comment by MarcMil** [comment]
Sadly, I am not able to access http://box.myqsc.com/ (is it available from China only?)

This might be a bug in apktool, however, I think, it may be because you have to use framework files in apktool in order to decode this app.
However, the use of framework files are unsupported by CodeInspect at the moment, since they are a bit clumsy. See
https://code.google.com/p/android-apktool/wiki/FrameworkFiles
for more details on framework files.

Where did you get the apk from? From your device?

See the issue on
https://code.google.com/p/android-apktool/issues/detail?id=465

When the resources cannot be decoded by apktool, CodeInspect cannot find them.

Sorry about that.

**Comment by flankerhqd** [comment]
Hi:

I've uploaded it to OneDrive, https://onedrive.live.com/redir?resid=A81B51F05D7E3C2F!7549&authkey=!AMSuPzuxPYEPnxs&ithint=file%2capk , if the original one is not available.

The apk is downloaded from apkdownloader, see http://apps.evozi.com/apk-downloader/.

**Comment by flankerhqd** [comment]
I tried the newest apktool 2.0.0rc4, and had the UndefinedResObject error. Agree with MarcMil.

**Comment by StevenArzt** [comment]
If it's an issue with apktool, we should maybe open an issue with them.

**Comment by MarcMil** [comment]
OK, I have created a bug report on the apktool.
https://code.google.com/p/android-apktool/issues/detail?id=779&thanks=779&ts=1426075581

**Comment by srasthofer** [comment]
Thanks @MarcMil

**Comment by MarcMil** [comment]
OK, I here is the solution which works for me:
You have a older version of your framework files installed, which causes apktool to fail creating valid xml files.

You have to remove them, so that apktool can install a newer version of them.
Linux
remove $HOME/apktool/framework/1.apk

Windows:
remove %HOMEPATH%\apktool\framework\1.apk

and reimport the apk into Codeinspect. Apktool will then copy its newer default framework to this place.

We should consider displaying an error message when this is the case and offer an option to remove the framework file.

**Comment by StevenArzt** [comment]
Great work. A message which explains the problem to the user and offers to fix it automatically would be awesome.

**Comment by MarcMil** [comment]
For now, we use our version of the framework as default.
